FROM python:3.12-slim-bookworm
RUN apt update &&  apt install  -y build-essential cargo
# RUN apk add --update musl-dev gcc cargo
# RUN pip install --upgrade pip
# RUN pip install bcrypt
RUN apt-get update \
    && apt-get -y install libpq-dev gcc \
    && pip install psycopg2

WORKDIR /tmp
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
RUN mkdir /app
WORKDIR /app
RUN python -m spacy download nl_core_news_lg
RUN python -m spacy download en_core_web_trf
RUN python -m spacy download fi_core_news_lg
RUN python -m spacy download fr_dep_news_trf
RUN python -m spacy download de_dep_news_trf
RUN python -m spacy download el_core_news_lg
RUN python -m spacy download it_core_news_lg
RUN python -m spacy download ja_core_news_trf
RUN python -m spacy download pt_core_news_lg
RUN python -m spacy download es_dep_news_trf
RUN python -m spacy download sv_core_news_lg


#COPY . .
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]