FROM python:3.12-slim-bookworm
RUN apt update &&  apt install  -y build-essential cargo
# RUN apk add --update musl-dev gcc cargo
# RUN pip install --upgrade pip
# RUN pip install bcrypt
RUN apt-get update \
    && apt-get -y install libpq-dev gcc \
    && pip install psycopg2

WORKDIR /tmp
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
RUN mkdir /app
WORKDIR /app
#COPY . .
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]