CREATE TABLE content_raw.sentence_elements_preview (
	lang varchar(12) NOT NULL,
	id int8 NOT NULL,
	"text" varchar(300) NOT NULL,
	elements jsonb DEFAULT '[]'::jsonb NULL,
	adverb1 text NULL,
	adverb2 text NULL,
	verb1 text NULL,
	verb2 text NULL,
	auxiliary_verb1 text NULL,
	auxiliary_verb2 text NULL,
	noun1 text NULL,
	noun2 text NULL,
	adjective1 text NULL,
	adjective2 text NULL,
	verb_count int2 DEFAULT 0 NULL,
	noun_count int2 DEFAULT 0 NULL,
	adjective_count int2 DEFAULT 0 NULL,
	adverb_count int2 DEFAULT 0 NULL,
	len_c int2 DEFAULT 0 NULL,
	len_elm int2 NULL,
	lang_extra jsonb DEFAULT '{}'::jsonb NULL,
	"options" _varchar DEFAULT ARRAY[]::character varying[] NULL,
	batch_id bpchar(36) NOT NULL,
	root_lemma varchar(100) NULL,
	noun1_lemma varchar(100) NULL,
	verb1_lemma varchar(100) NULL,
	root varchar(100) NULL,
	verb1_aux varchar(100) NULL,
	CONSTRAINT sentence_elements_new__pkey PRIMARY KEY (lang, id, batch_id)
);