DROP TABLE IF EXISTS content_raw.sentence_full;

CREATE TABLE content_raw.sentence_full (
	lang varchar(12) NOT NULL,
	id int8 NOT NULL,
	"text" varchar(300) NOT NULL,
	corpus varchar(30) NULL,
	options varchar(300)[] NULL,
	recording varchar(255) NULL,
	extra_recording varchar(255)[] NULL,
	elements jsonb DEFAULT '[]'::jsonb NULL,
	words varchar(100)[] NULL,
	adverb1 text NULL,
	adverb2 text NULL,
	verb1 text NULL,
	verb2 text NULL,
	auxiliary_verb1 text NULL,
	auxiliary_verb2 text NULL,
	noun1 text NULL,
	noun2 text NULL,
	adjective1 text NULL,
	adjective2 text NULL,
	verb_count int2 DEFAULT 0 NULL,
	noun_count int2 DEFAULT 0 NULL,
	adjective_count int2 DEFAULT 0 NULL,
	adverb_count int2 DEFAULT 0 NULL,
	len_c int2 DEFAULT 0,
	len_elm int2 DEFAULT 0,
	len_words int2 DEFAULT 0,
	reviewed boolean DEFAULT false NULL,
	review_comments text NULL,
	reviewed_by varchar(100) NULL,
	lang_extra jsonb DEFAULT '{}'::jsonb NULL,
	CONSTRAINT sentence_full_pkey PRIMARY KEY (lang, id)
);