CREATE TABLE content_raw.words_pos (
	lang varchar(12) NOT NULL,
	word varchar(100) NOT NULL,
	pos varchar(100) NOT NULL default ,
	root_count int4 DEFAULT 0 NULL,
	count int4 DEFAULT 0 NULL,
	lemma varchar(100) NOT NULL,
	rank int4 DEFAULT 0 NULL,
	wc1 int4 DEFAULT 0 NULL, 
    wc2 int4 DEFAULT 0 NULL,
    wc3 int4 DEFAULT 0 NULL,
    wc4 int4 DEFAULT 0 NULL,
    wc5 int4 DEFAULT 0 NULL,
    wc6 int4 DEFAULT 0 NULL,
    wc7 int4 DEFAULT 0 NULL,
    wc8 int4 DEFAULT 0 NULL,
    wc9 int4 DEFAULT 0 NULL,
    wc10 int4 DEFAULT 0 NULL,
    wc11 int4 DEFAULT 0 NULL,
    wc12 int4 DEFAULT 0 NULL,
    wc13 int4 DEFAULT 0 NULL,
    wc14 int4 DEFAULT 0 NULL,
    wc15 int4 DEFAULT 0 NULL,
    wc16 int4 DEFAULT 0 NULL,
    wc17_and_more int4 DEFAULT 0 NULL,
	CONSTRAINT words_pos_pkey PRIMARY KEY (lang, word, pos)
);